### ISSUE TITLE
Creating dynamic menu items

### ISSUE THREAD

**Issue by elmcapp** [chipjarred/MacMenuBar#6]
I am trying to create dynamic menu items but not sure how to code the following. I have a midiManager that will print an array of midi devices. I want to create a midi item that has the name of each device 

I am getting the following error
Argument type '()' does not conform to expected type 'MenuElement'

if as use as I get a different error
````
 StandardMenu(title: "Midi Devices")
            {
              midiManager.endpoints.outputs.forEach { device in
                TextMenuItem(title: device.name) { _ in
                  print(device.uniqueID)
                }
              }
            }
````

**Comment by chipjarred** [comment]
You're not far from having it.  Based on what it looks like you are trying to do in your code example, this should do the trick:

```swift
StandardMenu(title: "Midi Devices") 
{
    ForEach(midiManager.endpoints.outputs)
    { device in
        TextMenuItem(title: device.name) 
        {
            print(device.uniqueID)
        }
    }
}
```

This uses MacMenuBar's `ForEach` which works in a similar way as SwiftUI's `ForEach`.
